name: Build Image

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: 0 0 * * 0
  push:
    branches:
      - main

jobs:
  Image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: github.event_name == 'schedule' || github.event_name == 'push'
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Prep
        id: prep
        env:
          DBCRT: ${{ secrets.DBCRT }}
          DBKEY: ${{ secrets.DBKEY }}
          GHE_RUN: ${{ github.run_number }}
        run: |
          set -x
          mkdir -p secureboot
          echo $DBCRT | base64 --decode > secureboot/db.crt
          echo $DBKEY | base64 --decode > secureboot/db.key
          git fetch --all --tags
          TAG="$(git tag -l --points-at HEAD)"
          TAG=${TAG:-v1.4.0}
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=docker_tag::${TAG}-$(date +%Y%m%d)-$(printf "%0*d" 4 $GHE_RUN)
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: maulc
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker build
        env:
          TAG: ${{ steps.prep.outputs.tag }}
          VERS: ${{ steps.prep.outputs.docker_tag }}
        run: |
          set -x
          CURRENT_DATE=$(date '+%Y-%m-%dT%R:%S%z')
          SHA=$(git rev-parse --verify HEAD)
          URL=https://github.com/chrismaul/maul-os-k8s
          docker build \
            --build-arg VERS=$VERS \
            --pull --no-cache \
            -t maulc/maul-os-k8s:$VERS \
            --label "org.opencontainers.image.created=${CURRENT_DATE}" \
            --label "org.opencontainers.image.url=$URL" \
            --label "org.opencontainers.image.documentation=$URL" \
            --label "org.opencontainers.image.source=$URL/archive/$TAG.tar.gz" \
            --label "org.opencontainers.image.version=$VERS" \
            --label "org.opencontainers.image.revision=${SHA}" \
            .
          docker push maulc/maul-os-k8s:$VERS
